config/routes.rb
Rails.application.routes.draw do
  resource :github_webhooks, only: :create, defaults: { formats: :json }
  # get 'messages/create'
  # get 'chatrooms/show'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: "pages#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :arenas, only: [:create, :new, :show, :index] do
    resources :projects, only: [:create, :new, :show, :index]
    resources :tasks, only: [:create, :new, :show, :index]
    resource :chatroom, only: [:show] do
      resources :messages, only: [:create]
    end
  end

  resources :languages, only: [:show]
  get 'profile', to: 'profiles#show', as: :profile
end

app/views/shared/commit-ground/_arena_player_comments.html.erb
<div class="card large dashboard messages" data-controller="chatroom-subscription" data-chatroom-subscription-chatroom-id-value="<%= @arena.chatroom.id %>">
   <div id="messages" data-chatroom-subscription-target="messages">
      <% @arena.chatroom.messages.each do |message| %>
        <%= render "messages/message", message: message %>
      <% end %>
    </div>
    <%= simple_form_for [@arena, @arena.chatroom, Message.new], url: arena_chatroom_messages_path(@arena), html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, class: "d-flex submit-message" } do |f| %>
      <%= f.input :content,
        label: false,
        as: :string,
        placeholder: "Message ##{@arena.chatroom.name}",
        input_html: { class: "text-dark h-100" },
        wrapper_html: { class: "flex-grow-1 h-100" }
      %>
      <%= f.submit "Send", class: "btn btn-primary" %>
    <% end %>
</div>

app/views/shared/commit-ground/_arena_player_kpis.html.erb
<% player = @selected_player || current_user.arena_players.first %>
<% if player %>
  <% projects = player.projects %>
  <% project = projects.first if projects.any? %>
  <% tasks = player.tasks %>
  <% completed_tasks = tasks.select(&:done).count %>
  <% total_tasks = tasks.count %>
  <% task_completion_percentage = total_tasks.zero? ? 0 : (completed_tasks.to_f / total_tasks * 100).round %>
  <% player_rank = player.rank %>
  <% player_score = player.total_score %>

  <%   github_client = Octokit::Client.new(access_token: ENV['GITHUB_ACCESS_TOKEN']) %>
  <%   github_user = github_client.user(player.user.pseudo) %>
  <%   github_profile_url = github_user.html_url %>

  <div class="card large dashboard">
    <div class="d-flex justify-content-between">
      <div class="card-body">
        <div class="d-flex justify-content-around">
          <%= link_to github_profile_url, target: "_blank", class: "github-profile-link", data: { controller: "github-profile", action: "mouseenter->github-profile#showTooltip mouseleave->github-profile#hideTooltip" } do %>
            <%= image_tag(player.user.avatar_url, alt: player.user.pseudo, class: "rounded-circle github-avatar", style: "width: 40px; height: 40px;") %>
          <% end %>
          <h2><span class="badge bg-secondary"><%= player_rank %><%= case player_rank % 10  when 1 then 'st'  when 2 then 'nd'  when 3 then 'rd'  else 'th' end %></span></h2>
          <h2><span class="badge bg-warning"><%= player_score %> pts</span></h2>
          <% if project %>
            <h2 class="project-link">
              <span class="badge bg-primary">
                <i class="fab fa-github"></i>&nbsp;
                <%= link_to project.name, project.repo_url, class: "text-info project-link-text", target: "_blank" %>
              </span>
            </h2>
          <% end %>
        </div>
      </div>
    </div>
    <div class="card-body">
      <div class="d-inline-flex">
        <h5 class="card-title">Tasks</h5>
      </div>
      <div class="progress">
        <div class="progress-bar bg-warning" role="progressbar" style="width: <%= task_completion_percentage %>%;" aria-valuenow="<%= task_completion_percentage %>" aria-valuemin="0" aria-valuemax="100"><%= task_completion_percentage %>% completed</div>
      </div>
    </div>
    <div class="card-body">
      <div class="d-inline-flex">
        <h5 class="card-title">Weeks</h5>
      </div>
      <div class="progress">
        <div class="progress-bar progress-bar-weeks bg-secondary" role="progressbar" style="width: <%= (@current_week.to_f / @total_weeks * 100).round %>%;" aria-valuenow="<%= @current_week %>" aria-valuemin="0" aria-valuemax="100"><%= @current_week %> weeks</div>
      </div>
      <div class="d-flex justify-content-end">
        <p><%= @arena.end_date %></p>
      </div>
    </div>
  </div>
<% else %>
  <p>No player data available. Please select a player or join an arena.</p>
<% end %>

app/views/shared/commit-ground/_arena_player_prize.html.erb
<div class="card small dashboard no-overflow">
  <div class="row justify-content-center">
    <div class="mx-auto my-3" style="width: 70%;">
      <img src="<%= @arena.image_url %>" class="card-img-top pic-prize" alt="<%= @arena.name %>">
    </div>
    <h3 class="text-center mt-1">⚔️ <%= @arena.name %></h3>
  </div>
  <div class="prize justify-content-around my-2">
    <div class="column align-self-center">
      <h3><span class="badge bg-secondary">🏆 <%= @arena.prize %> €</span></h3>
    </div>
    <div class="column">
      <h5>🥇 <%= (@arena.prize*0.5).round %> €</h5>
      <h5>🥈 <%= (@arena.prize*0.3).round %> €</h5>
      <h5>🥉 <%= (@arena.prize*0.2).round %> €</h5>
    </div>
  </div>
</div>

app/views/shared/commit-ground/_arena_player_projects.html.erb
<% player = @selected_player || current_user.arena_players.first %>

<% if player %>
  <% projects = player.projects %>
  <% project = projects.first if projects.any? %>
  <% tasks_by_week = player.tasks.group_by(&:week_number) %>
  <% total_weeks = @total_weeks || 5 %> <!-- Default to 5 weeks if @total_weeks is not set -->
  <% current_week = @current_week || 1 %> <!-- Default to week 1 if @current_week is not set -->

  <div class="row" data-controller="week-selector task" data-week-selector-tasks-by-week="<%= tasks_by_week.to_json %>" data-task-task-ids-value="<%= player.tasks.map(&:id).to_json %>">
    <!-- Project Card with Week Selector -->
    <% if project %>
      <div class="col-md-6">
        <div class="card small dashboard">
          <div class="card-body">
            <h5 class="card-title">Sprint</h5>
            <div class="row">
              <% (1..total_weeks).each do |week| %>
                <div class="col-12">
                  <div class="form-check m-2">
                    <input class="form-check-input week-selector" type="radio" name="week" id="week<%= week %>" value="<%= week %>" data-week-selector-target="weekSelector" <%= 'checked' if week == current_week %>>
                    <label class="form-check-label" for="week<%= week %>">
                      W<%= week %> - <%= tasks_by_week[week]&.count || 0 %> Task(s) - <%= tasks_by_week[week]&.map(&:score)&.sum || 0 %> pts
                    </label>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <p>No projects available for this player.</p>
    <% end %>

    <!-- Task Card -->
    <div class="col-md-6">
      <div class="card small dashboard">
        <div class="card-body">
          <h5 class="card-title">Weekly Tasks<span id="current-week-number" data-week-selector-target="currentWeekNumber" style="display: none;"><%= current_week %></span></h5>
          <div id="task-list" data-week-selector-target="taskList">
            <% tasks_by_week[current_week]&.each do |task| %>
              <div class="task-item mt-2 align-items-center" data-task-id="<%= task.id %>" data-task-target="task">
                <div class="form-check">
                  <input class="form-check-input task-done" type="checkbox" value="" <%= 'checked' if task.done %> disabled>&nbsp;
                  <label class="form-check-label task-name <%= 'text-decoration-line-through' if task.done %>"><%=task.name%> - <%=task.score%> pts</label>
                  <i class="fa fa-check text-success ms-2 <%= 'd-none' unless task.done %>"></i>
                </div>
                <p class="task-description ps-2"><%= task.description %></p>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <p>No player data available. Please select a player or join an arena.</p>
<% end %>

app/views/shared/commit-ground/_arena_player_tasks.html.erb
<% player = @selected_player || current_user.arena_players.first %>

<% if player %>
  <div class="card small dashboard">
    <div class="row">
      <h5>All Projects</h5>
    </div>
    <ul class="list-group list-group-flush">
      <% player.projects.each do |project| %>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div>
            <h6 class="mb-1"><%= project.name %></h6>
            <small class="text-muted"><i class="fab fa-github"></i> <%= project.repo_url %></small>
          </div>
          <span class="badge bg-primary rounded-pill">Commits: <%= project.commits.count %></span>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/commit-ground/_arena_ranking.html.erb
<div class="card small dashboard">
  <div class="card-body">
    <div class="d-inline-flex">
      <h5 class="card-title light-gray">Ranking</h5>
    </div>
    <div class="list-group-flush">
      <% @arena_players.each_with_index do |arena_player, index| %>
        <%= link_to arena_path(arena_player.arena, player_id: arena_player.id), class: 'list-group-item list-group-item-action d-flex justify-content-between align-items-center hover-effect mt-3' do %>
          <div class="d-inline-flex">
            <%= image_tag(arena_player.user.avatar_url, alt: arena_player.user.pseudo, class: "rounded-circle me-3", style: "width: 40px; height: 40px;") %>
            <div class="d-block-flex">
              <p><%= arena_player.user.pseudo %> </p>
              <small class="text-muted score-points">Score: <%= arena_player.total_score %> pts</small>
            </div>
          </div>
          <span class="badge bg-primary rounded-pill"><%= arena_player.rank %></span>
        <% end %>
      <% end %>
    </div>
  </div>
</div>