config/routes.rb
Rails.application.routes.draw do
  resource :github_webhooks, only: :create, defaults: { formats: :json }
  # get 'messages/create'
  # get 'chatrooms/show'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: "pages#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :arenas, only: [:create, :new, :show, :index] do
    resources :projects, only: [:create, :new, :show, :index]
    resources :tasks, only: [:create, :new, :show, :index]
    resource :chatroom, only: [:show] do
      resources :messages, only: [:create]
    end
  end

  resources :languages, only: [:show]
  get 'profile', to: 'profiles#show', as: :profile
end

app/views/shared/_arena_player_chat.html.erb
<div class="row">
  <div class="col-md-6 card h-50" style="border-radius: 5%">
      <p>Large Card</p>
  </div>
</div>

app/views/shared/_arenacard.html.erb
<div class="row mb-4">
  <% @arenas.each_with_index do |arena, index| %>
    <div class="col-md-4 mt-4">
      <div class="card">
        <div>
          <% if arena.image_url.present? %>
            <img src="<%= arena.image_url %>" class="card-img-top pic" alt="<%= arena.name %>">
          <% end %>
        </div>
        <div class="card-body">
          <div class="d-flex justify-content-between align-items-center w-100">
            <h5 class="card-title text-primary"><%= arena.name %></h5>
            <a href="<%= arena_path(arena) %>" class="btn btn-primary button_radius">Join</a>
          </div>
          <div class="mt-2 d-flex flex-wrap justify-content-between align-items-center w-100">
            <span style="height: 20px; line-height: 20px;">
              <i class="fa-solid fa-calendar" style="color: #ffffff;"></i>
              <%= arena.start_date %>
            </span>
            <span style="height: 20px; line-height: 20px;">
              <i class="fa-solid fa-euro-sign" style="color: #ffffff;"></i>
              <%= arena.prize %>
            </span>
            <span style="height: 20px; line-height: 20px;">
              <i class="fa-solid fa-person" style="color: #ffffff;"></i>
              <%= arena.slots %>
            </span>
            <span style="height: 20px; line-height: 20px;">
              <%= arena.category.name %>
            </span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="flash flash-<%= key %> alert alert-dismissible fade show" role="alert"
  data-controller="flash">

    <span>
      <% if key == 'success' %>
        <strong>Yay!</strong> 🎉 <%= message %>
      <% elsif key == 'warning' %>
        <strong>Mmh</strong> 🤔 <%= message %>
      <% elsif key == 'danger' %>
        <strong>Oops!</strong> 😱 <%= message %>
      <% else %>
        <%= message %>
      <% end %>
    </span>
    &nbsp;
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer fixed-bottom">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid fixed-top navbarfixedtop">
    <div class="d-flex align-items-center">
      <%= link_to "#", class: "navbar-brand logo" do %>
        <%= image_tag "Logo_.png" %>
      <% end %>
      <span class="navbar-text">
        <% if current_user && current_user_active_arena %>
          <%= link_to 'CommitGround', arena_path(current_user_active_arena), class: 'nav-link d-inline p-0 nav-button' %>
        <% else %>
          <%= link_to 'No Active Arena', '#', class: 'nav-link d-inline p-0 nav-button' %>
        <% end %>
      </span>
      <span class="navbar-text ms-2">
        <%= link_to 'Join Arenas', arenas_path , class: 'nav-link d-inline p-0 nav-button'%>
      </span>
            <span class="navbar-text ms-2">
        <%= link_to 'New Arena', new_arena_path , class: 'nav-link d-inline p-0 nav-button'%>
      </span>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.avatar_url.nil? %>
                <%= image_tag "https://avatars.githubusercontent.com/u/583231?v=4", class: "avatar", alt: "avatar", class: "avatar", alt: "dropdown menu" %>
              <% else %>
                <%= image_tag current_user.avatar_url, class: "avatar", alt: "avatar", class: "avatar", alt: "dropdown menu" %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Profile", profile_path, class: "dropdown-item text-dark" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item text-dark" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item btn btn-primary">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>